
INSERT INTO categories VALUES (46, 'ESTUDIANTES', 58, 1);
INSERT INTO categories VALUES (76, 'PLAN DE ESTUDIOS', 58, 2);
INSERT INTO categories VALUES (67, 'OBJETIVOS EDUCACIONALES', 58, 3);
INSERT INTO categories VALUES (5, 'ATRIBUTOS DE EGRESO', 58, 4);
INSERT INTO categories VALUES (19, 'PERSONAL ACADÉMICO', 58, 5);
INSERT INTO categories VALUES (8, 'SOPORTE INSTITUCIONAL', 58, 6);
INSERT INTO categories VALUES (29, 'MEJORA CONTINUA', 58, 7);
INSERT INTO categories VALUES (25, 'ÁREA DISCIPLINAR DEL PROGRAMA EDUCATIVO', 58, 8);
