
INSERT INTO sections VALUES (33, 46, 'Admisión', 'temp', 1, true);
INSERT INTO sections VALUES (28, 76, 'Organización curricular', 'temp', 1, false);
INSERT INTO sections VALUES (52, 67, 'Definición y difusión de los objetivos educacionales del programa educativo', 'temp', 1, false);
INSERT INTO sections VALUES (61, 67, 'Valoración de los objetivos educacionales del programa educativo', 'temp', 2, false);
INSERT INTO sections VALUES (53, 5, 'Definición y difusión de los atributos de egreso', 'temp', 1, false);
INSERT INTO sections VALUES (30, 5, 'Valoración de los atributos de egreso', 'temp', 2, false);
INSERT INTO sections VALUES (93, 5, 'Logro de los atributos de egreso', 'temp', 3, false);
INSERT INTO sections VALUES (79, 19, 'Perfil del personal académico', 'temp', 1, false);
INSERT INTO sections VALUES (97, 8, 'Infraestructura y equipamiento', 'temp', 1, false);
INSERT INTO sections VALUES (10, 29, 'Proceso de mejora', 'temp', 2, false);
INSERT INTO sections VALUES (36, 46, 'Revalidación, equivalencia y reconocimiento de otros estudios', 'temp', 2, true);
INSERT INTO sections VALUES (65, 46, 'Privacidad de los datos del estudiante', 'temp', 3, true);
INSERT INTO sections VALUES (19, 46, 'Integridad académica', 'temp', 4, true);
INSERT INTO sections VALUES (89, 46, 'Trayectoria escolar', 'temp', 5, true);
INSERT INTO sections VALUES (11, 46, 'Asesoría y tutoría', 'temp', 6, true);
INSERT INTO sections VALUES (81, 46, 'Titulación', 'temp', 7, true);
INSERT INTO sections VALUES (55, 46, 'Comportamientos apropiados', 'temp', 8, true);
INSERT INTO sections VALUES (42, 76, 'Problemas de ingeniería complejos', 'temp', 2, true);
INSERT INTO sections VALUES (90, 76, 'Experiencia en diseño', 'temp', 3, true);
INSERT INTO sections VALUES (59, 76, 'Flexibilidad curricular', 'temp', 4, true);
INSERT INTO sections VALUES (21, 19, 'Suficiencia del personal académico', 'temp', 2, true);
INSERT INTO sections VALUES (14, 19, 'Distribución de actividades sustantivas', 'temp', 3, true);
INSERT INTO sections VALUES (57, 19, 'Evaluación y desarrollo de personal académico', 'temp', 4, true);
INSERT INTO sections VALUES (69, 19, 'Autoridad y responsabilidad del personal académico del plan de estudios', 'temp', 5, true);
INSERT INTO sections VALUES (64, 19, 'Selección, permanencia y retención del personal académico', 'temp', 6, true);
INSERT INTO sections VALUES (25, 8, 'Liderazgo institucional', 'temp', 2, true);
INSERT INTO sections VALUES (78, 8, 'Recursos financieros', 'temp', 3, true);
INSERT INTO sections VALUES (40, 29, 'Definición y justificación de los grupos de interés del programa educativo', 'temp', 1, true);
INSERT INTO sections VALUES (51, 25, 'Programas denominados Ingeniería en Ciencias Computacionales, Ingeniería en Computación o similares', 'temp', 1, true);
