
INSERT INTO standards VALUES (83, 28, 'Ciencias básicas', 'temp', false, 'temp', 1);
INSERT INTO standards VALUES (88, 28, 'Ciencias de la ingeniería', 'temp', false, 'temp', 2);
INSERT INTO standards VALUES (14, 28, 'Ingeniería aplicada y diseño en ingeniería.', 'temp', false, 'temp', 3);
INSERT INTO standards VALUES (11, 28, 'Ciencias sociales y humanidades', 'temp', false, 'temp', 4);
INSERT INTO standards VALUES (79, 28, 'Ciencias económico administrativas', 'temp', false, 'temp', 5);
INSERT INTO standards VALUES (25, 28, 'Cursos complementarios', 'temp', false, 'temp', 6);
INSERT INTO standards VALUES (6, 36, 'Revalidación, equivalencia y reconocimiento de otros estudios', 'temp', false, 'temp', 1);
INSERT INTO standards VALUES (64, 89, 'Trayectoria escolar', 'temp', false, 'temp', 1);
INSERT INTO standards VALUES (20, 11, 'Asesoría y tutoría', 'temp', false, 'temp', 1);
INSERT INTO standards VALUES (30, 42, 'Problemas de ingeniería complejos', 'temp', false, 'temp', 1);
INSERT INTO standards VALUES (77, 90, 'Experiencia en diseño', 'temp', false, 'temp', 1);
INSERT INTO standards VALUES (38, 59, 'Flexibilidad curricular', 'temp', false, 'temp', 1);
INSERT INTO standards VALUES (57, 52, 'Consistentes', 'temp', false, 'temp', 1);
INSERT INTO standards VALUES (45, 52, 'Congruentes', 'temp', false, 'temp', 2);
INSERT INTO standards VALUES (61, 52, 'Participativos', 'temp', false, 'temp', 3);
INSERT INTO standards VALUES (13, 52, 'Difundidos y actualizados', 'temp', false, 'temp', 4);
INSERT INTO standards VALUES (82, 61, 'Proceso de valoración', 'temp', false, 'temp', 1);
INSERT INTO standards VALUES (87, 61, 'Resultados de valoración', 'temp', false, 'temp', 2);
INSERT INTO standards VALUES (75, 61, 'Análisis de resultados', 'temp', false, 'temp', 3);
INSERT INTO standards VALUES (12, 53, 'Definición y difusión de los AE', 'temp', false, 'temp', 1);
INSERT INTO standards VALUES (67, 53, 'Equivalencia de los AE del PE con los del CACEI.', 'temp', false, 'temp', 2);
INSERT INTO standards VALUES (39, 53, 'Contribución de los AE a los OE del PE.', 'temp', false, 'temp', 3);
INSERT INTO standards VALUES (90, 30, 'Organización y compromiso', 'temp', false, 'temp', 1);
INSERT INTO standards VALUES (2, 30, 'Mapas curriculares', 'temp', false, 'temp', 2);
INSERT INTO standards VALUES (85, 30, 'Criterios de desempeño e indicadores', 'temp', false, 'temp', 3);
INSERT INTO standards VALUES (41, 30, 'Herramientas de valoración', 'temp', false, 'temp', 4);
INSERT INTO standards VALUES (84, 93, 'Resultados de la valoración', 'temp', false, 'temp', 1);
INSERT INTO standards VALUES (72, 93, 'Análisis de resultados del PE', 'temp', false, 'temp', 2);
INSERT INTO standards VALUES (59, 79, 'Cedulas 5.1.0', 'temp', false, 'temp', 1);
INSERT INTO standards VALUES (1, 79, 'Cedulas 5.1.1', 'temp', false, 'temp', 2);
INSERT INTO standards VALUES (17, 21, 'Suficiencia del personal académico', 'temp', false, 'temp', 1);
INSERT INTO standards VALUES (23, 14, 'Distribución de actividades sustantivas', 'temp', false, 'temp', 1);
INSERT INTO standards VALUES (35, 57, 'Evaluación y desarrollo de personal académico', 'temp', false, 'temp', 1);
INSERT INTO standards VALUES (92, 69, 'Autoridad y responsabilidad del personal académico del plan de estudios', 'temp', false, 'temp', 1);
INSERT INTO standards VALUES (95, 64, 'Selección, permanencia y retención del personal académico', 'temp', false, 'temp', 1);
INSERT INTO standards VALUES (96, 97, 'Servicios informáticos, de software y de información (bibliográficos)', 'temp', false, 'temp', 2);
INSERT INTO standards VALUES (81, 97, 'Infraestructura experimental', 'temp', false, 'temp', 3);
INSERT INTO standards VALUES (89, 40, 'Definición y justificación de los grupos de interés del programa educativo', 'temp', false, 'temp', 1);
INSERT INTO standards VALUES (74, 10, 'Participación de profesores y grupos de interés', 'temp', false, 'temp', 1);
INSERT INTO standards VALUES (56, 40, 'Planeación y mejora integral', 'temp', false, 'temp', 2);
INSERT INTO standards VALUES (21, 40, 'Acciones de mejora', 'temp', false, 'temp', 3);
INSERT INTO standards VALUES (51, 51, 'Programas denominados Ingeniería en Ciencias Computacionales, Ingeniería en Computación o similares', 'temp', false, 'temp', 1);
INSERT INTO standards VALUES (28, 33, 'Admisión', 'temp', true, 'temp', 1);
INSERT INTO standards VALUES (24, 65, 'Privacidad de los datos del estudiante', 'temp', true, 'temp', 1);
INSERT INTO standards VALUES (43, 19, 'Integridad académica', 'temp', false, 'temp', 1);
INSERT INTO standards VALUES (29, 55, 'Comportamientos apropiados', 'temp', true, 'temp', 1);
INSERT INTO standards VALUES (22, 81, 'Titulación', 'temp', true, 'temp', 1);
INSERT INTO standards VALUES (97, 97, 'Servicios académicos', 'temp', true, 'temp', 1);
INSERT INTO standards VALUES (80, 25, 'Liderazgo institucional', 'temp', true, 'temp', 1);
INSERT INTO standards VALUES (93, 78, 'Recursos financieros', 'temp', true, 'temp', 1);
